---

vm_name: GGA
vm_image_name: Debian10
vm_image_id: f7be72a3-1765-4212-8094-59c442201cb2
vm_flavor_name: m1.medium
vm_key_pair: rdallet-sbr

os_auth_url: https://genostack-api-keystone.genouest.org/v3
os_project_id: d84c93cbdb4e4b0a8a91ecdc4e7254f4
os_project_name: rdallet
os_user_domain: Users
os_project_domain_id: 0de861d3d0fc43eabf692d6dbb1cc257
os_user_name: rdallet
tenant_network: genouest-ext

terraform_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36643331613138663263623032396137333635373734383862306464366336393439643362326364
          3234656166316635356530373163333064346165663962650a666663383261306230306266376634
          35363261363436643236663363353132326565646261323038303731353834323666633232656466
          3836346566326636320a376164636430666162313132316264636534623761363561346263633231
          3834
